### PR TITLE
add note about configuring PR branch deletion in repository setting

### PR DESCRIPTION
**Pull request by joyeecheung**

### CODE REVIEW

**Comment by aduh95** [comment]
I feel quite strongly this is not the right approach, instead of more docs, let's have GitHub enforce it for us with https://github.com/nodejs/bluesky/settings/rules/2926087 and https://github.com/nodejs/bluesky/pull/16

**Comment by joyeecheung** [comment]
Do you happen to know how to write a rule set that

1. Disables direct commits to main from GitHub UI
2. Still allows commits pushed/removed from main from the CLI?

**Comment by aduh95** [comment]
I think when we need to push to `main`, we can temporarily disable the rule. For the automation, we can have the bot on the exception list

**Comment by aduh95** [comment]
I think that's fine, it's much easier for someone writing an automation to be forced to read a doc, rather than relying on contributors to refrain from doing a very common thing (deleting the head branch once the PR has merged)

**Comment by joyeecheung** [comment]
I think so far the incidents only happened when GitHub deleted the branch. Usually the action finishes in <30s which is not a lot of time to wait until you click another button to delete the branch.

**Comment by aduh95** [comment]
I've pushed another commit to https://github.com/nodejs/bluesky/pull/16 so the workflow doesn't use the deletable branch

**Comment by joyeecheung** [comment]
From https://github.com/nodejs/bluesky/pull/23 it seems the forks need to disable it too, which is a bit too much. I think trying to put the limitation in the base repo would be the best approach, so closing.

**Pull request closed without merging**
