### PR TITLE
add spanish repost

### PR DESCRIPTION
**Pull request by bmuenzenmeyer**
nice story here, five days after https://github.com/nodejs/bluesky/pull/33 helped get more people involved, we have spanish live at https://nodejs.org/es

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
also have https://bsky.app/profile/brianmuenzenmeyer.com/post/3ldluz75lmc27 as a spanish version, unsure how we feel about spamming both

**Comment by joyeecheung** [comment]
I feel that we should post the spanish version, but also it's a bit confusing that it's not mentioning https://nodejs.org/es in the post being reposted?

**Comment by bmuenzenmeyer** [comment]
Good feedback
Agree about the url. I got a bit confused because the handle is the url.

I can repost and update here when back at a computer

**Comment by bmuenzenmeyer** [comment]
@joyeecheung this is ready for re-review

**Review by aduh95 — APPROVED** [review]

**Review by AugustinMauroy — APPROVED** [review]

**Review by joyeecheung — APPROVED** [review]

**Pull request merged**
